package FlipApp;

/**
* FlipApp/FlipHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Flip.idl
* Sunday, April 22, 2018 10:22:44 PM CDT
*/

public final class FlipHolder implements org.omg.CORBA.portable.Streamable
{
  public FlipApp.Flip value = null;

  public FlipHolder ()
  {
  }

  public FlipHolder (FlipApp.Flip initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FlipApp.FlipHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FlipApp.FlipHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FlipApp.FlipHelper.type ();
  }

}
