package FlipApp;


/**
* FlipApp/Flip.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Flip.idl
* Sunday, April 22, 2018 10:22:44 PM CDT
*/

public interface Flip extends FlipOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Flip
